[package]
name = "html_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.19"
itertools = "0.12.1"
log = "0.4"
log4rs = "1.0"
tiny_http = "0.12.0"
serde = "1.0.201"
serde_json = "1.0.117"

[[bin]]
name = "serve"
path = "src/serve.rs"
